using EFCore10DeepDive.Data;
using EFCore10DeepDive.Models;
using EFCore10DeepDive.Services;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;

namespace EFCore10DeepDive.DemoStrategies;

/// <summary>
/// NEW in EF Core 10: Vector Search Support
/// </summary>
public class VectorSearchDemo : DemoBase
{
    private EmbeddingService _embeddingService = new();

    public override string FeatureName => "Vector Search (SQL Server 2025)";
    public override string Description => "Search using vector embeddings";

    protected override async Task ExecuteDemoAsync(AppDbContext context)
    {
        Console.WriteLine("Create products with vector embeddings");

        // Vector embeddings are automatically generated by VectorGenerationInterceptor
        var products = new List<Product>
        {
            new()
            {
                Name = "Wireless Gaming Mouse",
                Description = "High-precision gaming mouse with RGB lighting and programmable buttons",
                Category = "Gaming Accessories",
                Price = 79.99m,
                StockQuantity = 150
            },
            new()
            {
                Name = "Mechanical Keyboard RGB",
                Description = "Premium mechanical keyboard with RGB backlight and custom switches",
                Category = "Gaming Accessories",
                Price = 149.99m,
                StockQuantity = 85
            },
            new()
            {
                Name = "USB-C Hub Multi-Port",
                Description = "7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader",
                Category = "Computer Accessories",
                Price = 45.99m,
                StockQuantity = 200
            },
            new()
            {
                Name = "Noise Cancelling Headphones",
                Description = "Premium wireless headphones with active noise cancellation and 30h battery",
                Category = "Audio",
                Price = 299.99m,
                StockQuantity = 65
            },
            new()
            {
                Name = "Portable SSD 1TB",
                Description = "Ultra-fast portable solid state drive with USB-C connection",
                Category = "Storage",
                Price = 129.99m,
                StockQuantity = 120
            },
            new()
            {
                Name = "Gaming Headset RGB",
                Description = "Surround sound gaming headset with noise-cancelling mic and RGB lighting",
                Category = "Gaming Accessories",
                Price = 89.99m,
                StockQuantity = 95
            }
        };

        context.Products.AddRange(products);
        await context.SaveChangesAsync(); // Vector embeddings generated on save
        Console.WriteLine($"    [OK] Inserted {products.Count} products");

        Console.WriteLine("\nSearch: 'gaming equipment with RGB lights'");

        // Generate query embedding
        var searchText = "gaming equipment with RGB lights";
        SqlVector<float> queryVector = await _embeddingService.GenerateEmbeddingAsync(searchText);

        Console.WriteLine();

        Console.WriteLine("    1. Cosine Similarity (angle between vectors, best for text)");
        var cosineResults = await GetTopProductsAsync(context, queryVector, "cosine", 3);
        DisplayResults(cosineResults);

        Console.WriteLine("\n    2. Euclidean Distance (straight-line distance)");
        var euclideanResults = await GetTopProductsAsync(context, queryVector, "euclidean", 3);
        DisplayResults(euclideanResults);
    }

    private async Task<List<(string Name, string Category, string Description, double Distance)>> GetTopProductsAsync(
        AppDbContext context,
        SqlVector<float> queryVector,
        string metric,
        int count)
    {
        var results = await context.Products
            .OrderBy(p => EF.Functions.VectorDistance(metric, p.SearchVector, queryVector))
            .Take(count)
            .Select(p => new
            {
                p.Name,
                p.Category,
                p.Description,
                Distance = EF.Functions.VectorDistance(metric, p.SearchVector, queryVector)
            })
            .ToListAsync();

        return results.Select(r => (r.Name, r.Category, r.Description, r.Distance)).ToList();
    }

    private void DisplayResults(List<(string Name, string Category, string Description, double Distance)> results)
    {
        foreach (var result in results)
        {
            Console.WriteLine($"\t{result.Distance:F4} - {result.Name} - {result.Category}");
            Console.WriteLine($"\t\t{result.Description}");
        }
    }
}
